server:
  port: 8200

spring:
  application:
    name: gateway-server
#  cloud:
#    gateway:
#      # 路由规则
#      routes:
#        - id: product-service           # 路由 ID，唯一
#          uri: http://localhost:8101/   # 目标 URI，路由到微服务的地址
#          predicates:                   # 断言（判断条件）
#            - Path=/product/**          # 匹配对应 URL 的请求，将匹配到的请求追加在目标 URI 之后

#eureka:
#  instance:
#    hostname: 127.0.0.1
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

