server:
  port: 8080

spring:
  application:
    name: client-api
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: root
    password: whis.wang1992
    virtual-host: /
    connection-timeout: 15000


