server:
  port: 8102

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8100/eureka
#  instance:
#    prefer-ip-address: true
#    ip-address: 192.168.1.199
spring:
  application:
    name: eureka-client-two
